const dot=document.getElementById('curDot'),ring=document.getElementById('curRing');
let mx=0,my=0,rx=0,ry=0;
document.addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;dot.style.left=mx+'px';dot.style.top=my+'px';});
(function ar(){rx+=(mx-rx)*.13;ry+=(my-ry)*.13;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(ar);})();
document.querySelectorAll('a,button,.cs-card,.etl-body,.sk-tile,.cc-card,.pill').forEach(el=>{
  el.addEventListener('mouseenter',()=>{dot.style.width='16px';dot.style.height='16px';dot.style.background='#fb923c';ring.style.width='52px';ring.style.height='52px';ring.style.borderColor='#fb923c';});
  el.addEventListener('mouseleave',()=>{dot.style.width='10px';dot.style.height='10px';dot.style.background='var(--lav2)';ring.style.width='38px';ring.style.height='38px';ring.style.borderColor='var(--lav2)';});
});
window.addEventListener('scroll',()=>document.getElementById('nav').classList.toggle('scrolled',scrollY>60));
const ro=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('vis');});},{threshold:.12,rootMargin:'0px 0px -40px 0px'});
document.querySelectorAll('.rl,.rr,.ru').forEach(el=>ro.observe(el));
let pos=0;const CARD=364;
function slide(d){const tr=document.getElementById('carTrack');const max=tr.children.length-3;pos=Math.max(0,Math.min(max,pos+d));tr.style.transform='translateX(-'+(pos*CARD)+'px)';}

const expD={
  gt:{logo:'🐝',bg:'var(--mint3)',co:'Georgia Institute of Technology',ro:'Graduate Assistant · Scheller College of Business · Jan 2026 – Present · Atlanta, GA',items:[
    {m:'GenAI',s:'Curriculum',t:'<strong>MBA Technology Strategy Curriculum — Prof. Marco Ceccagnoli</strong> — Revamping Scheller College MBA coursework by creating business case studies that incorporate GenAI and ML applications into technology strategy frameworks used by MBA students.'},
    {m:'55K',s:'Attendees',t:'<strong>Smart Stadium — Bobby Dodd Stadium</strong> — Building a fan-engagement and real-time recommendation engine for Georgia Tech\'s football stadium. The platform recommends concessions, seating upgrades, and event experiences based on fan behavior and location.'},
    {m:'PMF',s:'Strategy',t:'<strong>Product-Market Fit & IoT Vendor Strategy</strong> — Leading PMF discovery for the Smart Stadium platform — conducting market sizing, stakeholder interviews with GT Athletics, and developing an IoT vendor lead-generation pipeline for stadium-wide sensor deployment.'},
    {m:'Spring',s:'Boot',t:'<strong>Backend Development</strong> — Architecting the Spring Boot framework backend for the fan-engagement platform, building REST APIs for recommendation delivery and real-time fan data aggregation from in-stadium sensors.'}
  ]},
  ptmsr:{logo:'💳',bg:'var(--peach3)',co:'Paytm — India\'s Largest Fintech',ro:'Senior Product Manager · Apr 2025 – Dec 2025 · Noida, India',items:[
    {m:'2 PMs',s:'+ 1 DA',t:'<strong>Team Leadership</strong> — Managed 2 Associate PMs and 1 Data Analyst. Stood up OKR cadence, ran Jira sprint planning, conducted weekly 1:1s, and acted as the main interface with Director/VP leadership for weekly business reviews across 5 orgs.'},
    {m:'$440M',s:'Revenue',t:'<span class="cs-link" onclick="openCS(0)"><strong>MDR Pricing Engine</strong> — Owned commercial MDR charging module for 30M gateway merchants, 10B transactions, $440M annual revenue. Built BIN-level differential charging for BNPL and super-premium cards. Unlocked $0.5M net new annualized PAT. <br><strong><i>Click to Read More</i></strong></span>'},
    {m:'300K',s:'Activations',t:'<span class="cs-link" onclick="openCS(4)"><strong>RuPay Card Activation Journeys</strong> — Launched RuPay Credit Card journeys on 3.5M MAU merchant app. Found 80% drop-off at discovery via Pulse funnel analytics. Built self-serve Payment Settings page. 300K monthly activations in 3 months. <br><strong><i>Click to Read More</i></strong></span>'}
  ]},
  ptmpm:{logo:'💳',bg:'var(--peach3)',co:'Paytm — India\'s Largest Fintech',ro:'Product Manager · Apr 2022 – Mar 2025 · Noida, India',items:[
    {m:'120K',s:'Churn Saved',t:'<strong>Subscription Charging Engine</strong> — Architected dynamic rental charging for 9M+ mPOS/Soundbox devices. Integrated CleverTap offers, CRON-based billing, retry logic (like ACH returns in US). Reduced annual device churn by 120K units via A/B-tested dynamic pricing.'},
    {m:'$540K',s:'Cost Saved',t:'<span class="cs-link" onclick="openCS(3)"><strong>Salesforce → Custom Onboarding Engine</strong> — Migrated 2.5M annual merchants off $540K/yr Salesforce via 3-phase shadow-mode rollout. Eliminated 6 fragile integrations, reduced fraud 60% through native KYB, established Central Data Store as single source of truth. <br><strong><i>Click to Read More</i></strong></span>'},
    {m:'$400K',s:'Saved/yr',t:'<span class="cs-link" onclick="openCS(1)"><strong>Interchange Cost Reconciliation</strong> — Discovered $300M cost center had zero automated auditing. Built 15,000-rule reconciliation engine. Caught $300K in acquirer overcharges (Axis Bank misclassifying cards), prevented $400K annual leakage. <br><strong><i>Click to Read More</i></strong></span>'},
    {m:'10M',s:'Invoices/mo',t:'<span class="cs-link" onclick="openCS(2)"><strong>Project BINARY — Invoicing Automation</strong> — Manual 50-person team invoicing 30M merchants. Built SAP Pre-Processor middleware. 10M invoices/month automated, 80% faster cycle (9d→1d), team 50→5, 4% lower contact-center volume. <br><strong><i>Click to Read More</i></strong></span>'},
    {m:'$2M',s:'New Revenue',t:'<strong>Subscription Payments Launch (0→1)</strong> — Researched 3 new verticals (Education, SIP investing, Dating apps), interviewed 60+ merchants, ran 5-merchant pilot. Launched India\'s first proper recurring billing on Paytm, generating $2M in net new annual revenue.'},
    {m:'35K',s:'Profiles Fixed',t:'<strong>KYB/AML Compliance Platform</strong> — Integrated Karza APIs (Socure equivalent) for bulk KYB. Built AML screening for sanctions lists + chargeback ratio monitoring. SQL analysis on 30M users corrected 35K legacy profile issues. Chargebacks dropped 60% vs generic launches.'}
  ]},
  hsbc:{logo:'🏦',bg:'var(--lav3)',co:'HSBC',ro:'Project Manager — MBA Summer Intern · May 2021 – Jun 2021 · Remote',items:[
    {m:'Research',s:'Project',t:'<strong>Payroll Portfolio Competitive Benchmarking</strong> — Led competitive benchmarking of HSBC\'s Payroll portfolio to build a value proposition discovery tool for retail customers, mapping differentiators against competitor offerings across the Indian banking landscape.'}
  ]},
  infosys:{logo:'💻',bg:'var(--yellow)',co:'Infosys',ro:'Sr. Software Engineer — Specialist Programmer · Aug 2019 – Aug 2020 · Hyderabad',items:[
    {m:'25x',s:'Agents',t:'<strong>Service Platform Optimization</strong> — Managed SDLC and architected high-level designs for a service platform scaled to 25x service agents. Improved CSAT by 50% through targeted performance and UX improvements.'},
    {m:'6',s:'Sprints',t:'<strong>E-Commerce Progressive Web App</strong> — Built end-to-end PWA using full MERN stack (MongoDB, Express, React, Node). Shipped in 6 sprints with complete automation testing coverage. This engineering experience gave me the technical empathy I rely on daily as a PM.'}
  ]}
};

function openExp(k){const d=expD[k];const ml=document.getElementById('mLogo');ml.textContent=d.logo;ml.style.background=d.bg;ml.style.fontSize='28px';document.getElementById('mCo').textContent=d.co;document.getElementById('mRo').textContent=d.ro;document.getElementById('mItems').innerHTML=d.items.map(i=>'<div class="mi"><div class="mi-m">'+i.m+'<small>'+i.s+'</small></div><div class="mi-t">'+i.t+'</div></div>').join('');document.getElementById('expMO').classList.add('open');document.body.style.overflow='hidden';}
function closeExpMO(e){if(e.target===document.getElementById('expMO'))closeExpMOD();}
function closeExpMOD(){document.getElementById('expMO').classList.remove('open');document.body.style.overflow='';}

const csD=[
  {em:'💳',bg:'linear-gradient(135deg,var(--peach3),var(--yellow))',t:'MDR Pricing Engine — $440M Revenue Portfolio',s:'Paytm · Monetization · Pricing Strategy · 2022–2025',
  ch:'I owned the MDR (Merchant Discount Rate) charging module for 30M merchants across 10B+ annual transactions. The system treated all card types identically — BNPL plans (Affirm/Klarna equivalents) and super-premium cards (Amex Centurion equivalents) were processed at standard rates, causing massive margin leakage. GMV tiers for Credit Cards and EMI were tracked separately, so merchants couldn\'t consolidate volume to hit discount thresholds.',
  so:'I upgraded Paytm\'s in-house Card BIN center to detect card category (retail, corporate, co-branded, super-premium) and coordinated with Visa, Mastercard, and 7 card-issuing banks to validate BIN ranges. Fixed the GMV tier logic by consolidating Credit Card and EMI GMV into one unified bucket. Built a fallback cascade preventing zero-fee transactions. Added instrument-level revenue split to Finance MIS and designed a Leadership dashboard showing MDR revenue vs. interchange cost per instrument type.',
  out:[{n:'$440M',l:'Revenue Portfolio'},{n:'$0.5M',l:'Net New Annual PAT'},{n:'700K+',l:'Merchants Corrected'},{n:'4',l:'New Instruments Enabled'}],
  lrn:'Pricing is a product. Turning a static rate spreadsheet into a dynamic rule engine that reads BIN-level transaction attributes made pricing a strategic lever, not a Finance manual exercise. The entire margin unlock came from data analysis — no new merchant fees were introduced.'},

  {em:'🔁',bg:'linear-gradient(135deg,var(--lav3),var(--mint3))',t:'Interchange Cost Reconciliation — $300M Cost Center',s:'Paytm · Operational Efficiency · Revenue Defense · 2023–2025',
  ch:'Payment processing costs to acquiring banks totaled $300M annually — Paytm\'s second-largest cost driver. Reconciliation was entirely manual and only covered the top 50 merchants out of 30M. I ran a SQL grouping analysis on Card + Merchant ID combinations and found Axis Bank (JPMorgan Chase equivalent) had overcharged $3,000 for a single merchant by misclassifying a retail debit card as a corporate card. Extrapolating even a 0.1% error rate across 10B transactions implied millions in undetected leakage.',
  so:'I mapped 15,000+ pricing rule combinations across card network, merchant category, and negotiated rates. Instead of building from scratch, I reused the existing MDR charging engine — parameterizing it to compute expected bank cost per transaction. Built an SFTP pipeline receiving the bank\'s daily transaction files, compared against our expected cost on a primary key (Transaction ID + Card + Merchant), and auto-emailed discrepancy reports to Finance. Added Maker-Checker UI for bulk rule upload with full audit trail.',
  out:[{n:'$400K+',l:'Annual Revenue Saved'},{n:'$300K',l:'Acquirer Overcharges Found'},{n:'$300M',l:'Cost Base Now Monitored'},{n:'15K+',l:'Pricing Rules Mapped'}],
  lrn:'Building an internal shadow calculation engine to audit vendor invoices at scale is a fundamental requirement for any payment processor at volume. You cannot manage what you cannot measure — and nobody was measuring this $300M blind spot.'},

  {em:'📄',bg:'linear-gradient(135deg,var(--mint3),var(--lav3))',t:'Project BINARY — Invoicing Automation for 30M Merchants',s:'Paytm · Digital Transformation · Financial Automation · 2022–2024',
  ch:'Invoicing for 30M merchants was handled manually by a 50-person Finance team using Excel files. The process had a 9-day cycle time, required manual data enrichment for Profit Centers and GL Codes, and multiple invoices per merchant caused confusion and support tickets. For enterprise merchants with multi-state locations, there was no way to consolidate billing.',
  so:'I designed "BINARY" — an SAP Pre-Processor middleware that consumed daily MIS reports, aggregated charges at the Merchant-Instrument level, and prepared structured data for SAP invoice creation. Used the Business Partner model: a single merchant could hold multiple roles (Payment Gateway, Device Rental, Audio Confirmation Device) — all consolidated into one invoice. Parsed Federal Tax IDs (EIN equivalents) to map Parent/Child enterprise hierarchies. Built a Maker-Checker frontend for Finance with role-based access and a 24/7 merchant-facing invoice download portal.',
  out:[{n:'10M',l:'Invoices/Month Automated'},{n:'80%',l:'Cycle Time Reduction (9d→1d)'},{n:'50→5',l:'Ops Team Headcount'},{n:'4%',l:'Contact Center Volume Down'}],
  lrn:'The biggest unlock was merchant-facing invoice visibility — not just backend automation. Once merchants could download invoices 24/7 and see line items, dispute volume dropped before we finished resolving all backend edge cases.'},

  {em:'🔄',bg:'linear-gradient(135deg,var(--yellow),var(--peach3))',t:'Salesforce → Custom Onboarding Engine Migration',s:'Paytm · Digital Transformation · Merchant Onboarding · 2022–2023',
  ch:'At 2.5M new merchants per year, Salesforce licensing costs had hit $540K annually. Salesforce lacked native KYB validation hooks, so fake merchant applications slipped through. The system also had 6 fragile point-to-point integrations with downstream systems, causing data inconsistencies that generated incorrect fee charges for merchants.',
  so:'Ran the migration in 3 phases to avoid disrupting live acquisition. Phase 1: Shadow Mode — applications flowed through Salesforce but mirrored into the new engine to validate schemas without affecting live traffic. Phase 2: Partial Cutover — new signups routed to the new engine while Salesforce remained active for historical merchants. Phase 3: Batch Migration — exported, cleaned, and validated millions of historical records before final import. Built an API gateway handling onboarding across multiple acquiring banks using penny drop verification, name match, and async callbacks. Established Central Data Store as the single system of record with bidirectional API sync eliminating all 6 legacy integrations.',
  out:[{n:'$540K',l:'Annual Licensing Eliminated'},{n:'60%',l:'Fraud Reduction'},{n:'2.5M',l:'Annual Merchants Maintained'},{n:'6',l:'Legacy Integrations Removed'}],
  lrn:'Phased rollouts using shadow mode are critical for zero-downtime migrations on live acquisition funnels. The 3-month migration with continuous validation meant we never dropped a single merchant application — and data quality improvements paid dividends every sprint after.'},

  {em:'📱',bg:'linear-gradient(135deg,var(--mint3),var(--yellow))',t:'RuPay Card Activation — 300K Monthly Activations',s:'Paytm · Merchant UX · Growth · 2024–2025',
  ch:'RuPay Credit Cards working on UPI rails represented a major growth opportunity, but adoption was flat despite the feature being technically live. I conducted VoC research with 50+ merchants segmented by business type, size, and existing payment methods to avoid bias. The finding: merchants had no idea they could accept RuPay Credit Cards via QR — the option was buried 3 levels deep in a legacy "My Services" menu.',
  so:'Built funnel analysis using Pulse event analytics (merchant_id, timestamp, OS, app version, event names) and tracked the journey from App Open to Activation Success. Found an 80% drop-off right at the My Settings page — discovery friction, not product rejection. Redesigned into a dedicated "Payments Settings" page with self-serve toggles and transparent fee disclosures per transaction type. Created CleverTap activation nudges showing merchants their average revenue uplift from enabling cards. Built a proactive deactivation bottom-sheet to provide educational pricing info when merchants tried to turn off a payment method.',
  out:[{n:'300K',l:'Monthly Activations'},{n:'80%',l:'Drop-Off Found & Fixed'},{n:'3mo',l:'To Scale Results'},{n:'#3',l:'Card Instrument on Platform'}],
  lrn:'Never assume low adoption means a bad product. Always start with funnel analysis and distinguish discovery friction from activation friction — they require completely different solutions. The 80% drop-off at My Settings told us exactly where to invest, not what to rebuild.'},

  {em:'🏟️',bg:'linear-gradient(135deg,var(--mint3),var(--lav3))',t:'Smart Stadium — Fan Engagement AI Platform',s:'Georgia Tech · AI Product · Recommendation Systems · 2026',
  ch:'Bobby Dodd Stadium hosts ~55,000 Georgia Tech football fans per game, but the in-stadium experience is fragmented — no personalized recommendations for concessions, seat upgrades, or merchandise. Fans with premium tickets don\'t get premium digital experiences. The Athletic Department lacked real-time data infrastructure to understand fan behavior at scale.',
  so:'Leading PMF discovery and product strategy for a fan-engagement AI platform. Conducting stakeholder interviews with GT Athletics leadership, building market sizing models for IoT-enabled stadiums, and developing IoT vendor lead-generation strategy to build the sensor infrastructure needed for real-time fan data. Simultaneously architecting the Spring Boot backend with REST APIs for recommendation delivery. The recommendation engine will use fan location, purchase history, and game context to surface hyper-relevant suggestions in real time.',
  out:[{n:'55K',l:'Attendees / Game'},{n:'AI',l:'Recommendation Engine'},{n:'IoT',l:'Vendor Pipeline'},{n:'Live',l:'GT Project'}],
  lrn:'Stadium tech is a forcing function for real-time product design — decisions must happen in seconds while a fan is walking to the concession stand. This project is teaching me to design for ultra-low latency UX backed by solid ML infrastructure, which translates directly to payment product design.'}
];

function openCS(i){const d=csD[i];const b=document.getElementById('csmBanner');b.textContent=d.em;b.style.background=d.bg;b.style.fontSize='60px';document.getElementById('csmTtl').textContent=d.t;document.getElementById('csmSub').textContent=d.s;document.getElementById('csmBody').innerHTML='<div class="csm-sec"><h4>🎯 The Challenge</h4><p>'+d.ch+'</p></div><div class="csm-sec"><h4>💡 My Approach</h4><p>'+d.so+'</p></div><div class="csm-sec"><h4>📈 Results</h4><div class="csm-res">'+d.out.map(o=>'<div class="csr"><div class="csr-n">'+o.n+'</div><div class="csr-l">'+o.l+'</div></div>').join('')+'</div></div><div class="csm-sec"><h4>🧠 Key Learning</h4><p>'+d.lrn+'</p></div>';document.getElementById('csmoOv').classList.add('open');document.body.style.overflow='hidden';}
function closeCSmO(e){if(e.target===document.getElementById('csmoOv'))closeCSMOD();}
function closeCSMOD(){document.getElementById('csmoOv').classList.remove('open');document.body.style.overflow='';}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeExpMOD();closeCSMOD();}});
